// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRiRvgWNwDeDPltENrEv-GrcXdCYkIlZ8',
    appId: '1:503669006055:web:11c16715826596da244c42',
    messagingSenderId: '503669006055',
    projectId: 'abiyeapp',
    authDomain: 'abiyeapp.firebaseapp.com',
    storageBucket: 'abiyeapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtQqq2MDMBIwAIjv5Jnu7cMbrwjIEZGu8',
    appId: '1:503669006055:android:468bdc543e34c386244c42',
    messagingSenderId: '503669006055',
    projectId: 'abiyeapp',
    storageBucket: 'abiyeapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw781Y9tfDTonlnXKsuWtu7fZXufThccs',
    appId: '1:503669006055:ios:0bdb1af5e3f39009244c42',
    messagingSenderId: '503669006055',
    projectId: 'abiyeapp',
    storageBucket: 'abiyeapp.firebasestorage.app',
    iosBundleId: 'com.example.abiyeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw781Y9tfDTonlnXKsuWtu7fZXufThccs',
    appId: '1:503669006055:ios:0bdb1af5e3f39009244c42',
    messagingSenderId: '503669006055',
    projectId: 'abiyeapp',
    storageBucket: 'abiyeapp.firebasestorage.app',
    iosBundleId: 'com.example.abiyeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRiRvgWNwDeDPltENrEv-GrcXdCYkIlZ8',
    appId: '1:503669006055:web:5f3e0d15c87e419e244c42',
    messagingSenderId: '503669006055',
    projectId: 'abiyeapp',
    authDomain: 'abiyeapp.firebaseapp.com',
    storageBucket: 'abiyeapp.firebasestorage.app',
  );

}